### ISSUE TITLE
Condition with return 

### ISSUE THREAD

**Issue by IanaKhitsko** [mariannasnitko/euro-diffusion#5]
https://github.com/mariannasnitko/euro-diffusion/blob/c8c13bcc7e4a5a47c84ca314017a150cfe7764e4/euro-diffusion/validation.js#L9

return (coord >= countryConstants.MIN_COORD && coord <= countryConstants.MAX_COORD);
  or combine with previous condition

**Comment by electricsoul-ux** [comment]
Done
