### ISSUE TITLE
Redundant local

### ISSUE THREAD

**Issue by IanaKhitsko** [mariannasnitko/euro-diffusion#6]
https://github.com/mariannasnitko/euro-diffusion/blob/c8c13bcc7e4a5a47c84ca314017a150cfe7764e4/euro-diffusion/map.js#L13

remove local variable

**Comment by IanaKhitsko** [comment]
https://github.com/mariannasnitko/euro-diffusion/blob/c8c13bcc7e4a5a47c84ca314017a150cfe7764e4/euro-diffusion/map.js#L19

same here

**Comment by electricsoul-ux** [comment]
Done
